---
abstract: 'build a '
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.57
configure_requires:
  ExtUtils::MakeMaker: 6.57
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Nginx
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  Text::Template: 1.2
  autodie: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
